# Generated by Django 3.2.9 on 2021-12-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='some_trash_column',
        ),
    ]
