# Generated by Django 3.2.9 on 2021-12-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211206_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradmin',
            name='login',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userregular',
            name='login',
            field=models.CharField(max_length=20),
        ),
    ]
