# Generated by Django 3.2.9 on 2021-12-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211204_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregular',
            name='is_approved',
            field=models.BooleanField(default=0),
        ),
    ]
